# Writes embedded_data.rb: the crate's data/*.json as string constants, so
# the compiled binary carries them the way include_str! does for the crate.
#
#   ruby gen_data.rb

TERM = "AIRPORT_FINDER_DATA"
root = File.expand_path("..", __dir__)
out = +"# Generated by gen_data.rb from ../data -- do not edit.\nmodule AirportFinder\n"
[["AIRPORTS_JSON", "airports.json"], ["COUNTRIES_JSON", "countries.geojson"]].each do |const, file|
  json = File.read(File.join(root, "data", file))
  abort "#{file}: a line equals the heredoc terminator #{TERM}" if json.each_line.any? { |l| l.chomp == TERM }
  out << "  #{const} = <<'#{TERM}'\n" << json
  out << "\n" unless json.end_with?("\n")
  out << "#{TERM}\n"
end
out << "end\n"
File.write(File.join(__dir__, "embedded_data.rb"), out)
