#!/usr/bin/env bash
# Prepares the C sources of the superwings-spinel Python package and builds
# its library in place:
#
#   python/csrc/   airport_finder_ext.{c,h} (spinel --ext-init, the data
#                  embedded), shim.c, Spinel's runtime sources (as
#                  `spin ext build` vendors them) and build_flags.txt (the
#                  cflags and defines `spinel --print-build` names)
#   python/superwings_spinel/libairport_finder_spinel.so
#
#   SPINEL=~/projects/spinel/spinel ext/build.sh
#
# csrc/ is what the sdist ships: from it, python/setup.py builds the same
# library with a C compiler alone.
set -euo pipefail
cd "$(dirname "$0")/.."

SPINEL=${SPINEL:-spinel}
CC=${CC:-cc}
E=AirportFinderExt
ENTRIES=$E.find,$E.country_at,$E.string,$E.airport,$E.airport_record,$E.set_new,$E.set_free,$E.set_size
ENTRIES=$ENTRIES,$E.set_include,$E.set_missing,$E.set_nearest,$E.set_resolve,$E.out_index,$E.out_km
CSRC=python/csrc

[ -f embedded_data.rb ] || ruby gen_data.rb
rm -rf "$CSRC"
mkdir -p "$CSRC/mruby"
"$SPINEL" ext/airport_finder_ext.rb -c --no-line-map -o "$CSRC/airport_finder_ext.c" --force \
  --ext-init af_ext_init --ext-entry "$ENTRIES" --print-build > "$CSRC/ingredients.txt"
cp ext/shim.c "$CSRC/"

# The runtime, flat beside the generated C (basenames are unique across
# lib/ and lib/regexp/); <mruby/*.h> keep their directory.
rt=$(sed -n 's/^include //p' "$CSRC/ingredients.txt" | head -1)
for f in "$rt"/*.c "$rt"/*.h "$rt"/regexp/*.c "$rt"/regexp/*.h "$rt"/regexp/*.inc "$rt"/regexp/shim/*.h; do
  cp "$f" "$CSRC/"
done
cp "$rt"/regexp/shim/mruby/*.h "$CSRC/mruby/"
{
  echo "# Generated by ext/build.sh from: $("$SPINEL" --version)"
  grep -E '^(cflag|define) ' "$CSRC/ingredients.txt"
} > "$CSRC/build_flags.txt"
rm "$CSRC/ingredients.txt"

# The same build setup.py does, for working on the package in place.
flags=()
while read -r kind value; do
  case $kind in cflag | define) flags+=("$value") ;; esac
done < "$CSRC/build_flags.txt"
case $(uname) in
  Darwin) strip_unused=-Wl,-dead_strip ;;
  *) strip_unused=-Wl,--gc-sections ;;
esac
"$CC" -O2 -fPIC -shared -fvisibility=hidden -ffunction-sections -fdata-sections -w \
  "${flags[@]}" -I"$CSRC" "$CSRC"/*.c -lm "$strip_unused" \
  -o python/superwings_spinel/libairport_finder_spinel.so
echo "built python/superwings_spinel/libairport_finder_spinel.so from $CSRC ($(ls "$CSRC" | wc -l | tr -d ' ') files)"
